// <auto-generated />
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;

public sealed class dbo_spEnrollStudent_Input
{
    public string FirstName { get; init; }
    public string LastName { get; init; }
    public short Age { get; init; }
    public decimal GPA { get; init; }
    public (string LocationName, int Level)[] ClassesToEnroll { get; init; }
}

public sealed class dbo_spEnrollStudent_Row
{
    public string FirstName { get; init; }
    public string LastName { get; init; }
    public short? Age { get; init; }
    public decimal? GPA { get; init; }
}

public partial class dbo_spEnrollStudent_ProcClient
{
    private readonly string _connectionString;
    private readonly bool _useDefaultRetryOptions;
    public dbo_spEnrollStudent_ProcClient(string connectionString,
        bool useDefaultRetryOptions)
    {
        _connectionString = connectionString;
        _useDefaultRetryOptions = useDefaultRetryOptions;
    }

    public async Task<List<dbo_spEnrollStudent_Row>> ExecuteAsync(
        dbo_spEnrollStudent_Input input,
        DbConnection? existingConnection = null,
        CancellationToken ct = default)
    {
        DbConnection? connection = existingConnection;
        if (connection == null)
        {
            connection = new SqlConnection(_connectionString);
        }
        using var cmd = connection.CreateCommand();
        cmd.CommandText = "[dbo].[spEnrollStudent]";
        cmd.CommandType = CommandType.StoredProcedure;

        AddParam(cmd, "@FirstName", System.Data.SqlDbType.VarChar, input.FirstName, false);
        AddParam(cmd, "@LastName", System.Data.SqlDbType.VarChar, input.LastName, false);
        AddParam(cmd, "@Age", System.Data.SqlDbType.SmallInt, input.Age, false);
        AddParam(cmd, "@GPA", System.Data.SqlDbType.Decimal, input.GPA, false);
        cmd.Parameters.Add(ToTvpClassesToEnroll("@ClassesToEnroll", "[dbo].[ClassesType]", input.ClassesToEnroll));

        OnBeforeExecute?.Invoke(cmd);

        if (connection.State != ConnectionState.Open)
            await connection.OpenAsync(ct).ConfigureAwait(false);


        using var reader = await cmd.ExecuteReaderAsync(CommandBehavior.SequentialAccess, ct).ConfigureAwait(false);
        var list = new List<dbo_spEnrollStudent_Row>(capacity: 64);
        while (await reader.ReadAsync(ct).ConfigureAwait(false))
        {
            list.Add(new dbo_spEnrollStudent_Row
            {
                FirstName = reader.IsDBNull(0) ? null : reader.GetString(0),
                LastName = reader.IsDBNull(1) ? null : reader.GetString(1),
                Age = reader.IsDBNull(2) ? default(short?) : reader.GetInt16(2),
                GPA = reader.IsDBNull(3) ? default(decimal?) : reader.GetDecimal(3),
            });
        }
        if (existingConnection == null)
        {
            connection.Dispose();
        }
        return list;
    }

    public Action<DbCommand>? OnBeforeExecute { get; set; }

    private static void AddParam(DbCommand cmd, string name, System.Data.SqlDbType sqlDbType, object? value, bool isOutput)
    {
        var p = new SqlParameter(name, sqlDbType)
        {
            Direction = isOutput ? ParameterDirection.InputOutput : ParameterDirection.Input,
            Value = value ?? DBNull.Value
        };
        cmd.Parameters.Add(p);
    }

    
        private static SqlParameter ToTvpClassesToEnroll(string name,
            string typeName,
            (string LocationName, int Level)[] rows)
        {
            var table = new System.Data.DataTable();
            table.Columns.Add("LocationName", typeof(string));
            table.Columns.Add("Level", typeof(int));
            foreach (var r in rows) 
            {
                table.Rows.Add(r.LocationName, r.Level); 
            }
            return new SqlParameter(name, SqlDbType.Structured) { TypeName = typeName, Value = table };
        }        

}