using System.Linq;
using Puppy.Ado.SourceGenerator.Models;

namespace Puppy.Ado.SourceGenerator
{
    public class StoreProcedureTextGenerator
    {
        public static string EmitProcedure(StoredProcedureModel p)
        {
            var inputDtoName = $"{p.ClrName}_Input";
            var outputDtoName = $"{p.ClrName}_Row";
            var paramProps = string.Join("\n", p.Parameters.Select(par =>
                $"    public {par.ClrName} {SqlModelTextMapper.ToPascal(SqlModelTextMapper.TrimAt(par.Name))} {{ get; init; }}"));

            var addParams = string.Join("\n", p.Parameters.Select(BuildParamAddition));
            var tvpMethods = p.Parameters
                .Where(IsTableValueParam)
                .Select(p => GenerateTableValueParamMapMethod(p.Name, p.ClrName));

            var hasResult = p.ResultSets.FirstOrDefault();
            var dtoProps = hasResult is null ? "" :
                string.Join("\n", hasResult.Columns.Select(c =>
                    $"    public {ClrTypeMapper.ToClrType(c.SqlType, c.IsNullable)} {SqlModelTextMapper.ToPascal(c.Name)} {{ get; init; }}"));

            var readCols = hasResult is null ? "" :
                string.Join("\n", hasResult.Columns.Select(MapResultColumn));

            var readBlock = hasResult is null ? "await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);\n        return new List<object>(0);" : $@"
        using var reader = await cmd.ExecuteReaderAsync(CommandBehavior.SequentialAccess, ct).ConfigureAwait(false);
        var list = new List<{outputDtoName}>(capacity: 64);
        while (await reader.ReadAsync(ct).ConfigureAwait(false))
        {{
            list.Add(new {outputDtoName}
            {{
{readCols}
            }});
        }}
        if (existingConnection == null)
        {{
            connection.Dispose();
        }}
        return list;";

            return $@"// <auto-generated />
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;

public sealed class {inputDtoName}
{{
{paramProps}
}}

{(hasResult is null ? "" : $@"public sealed class {outputDtoName}
{{
{dtoProps}
}}")}

public partial class {p.ClrName}_ProcClient
{{
    private readonly string _connectionString;
    private readonly bool _useDefaultRetryOptions;
    public {p.ClrName}_ProcClient(string connectionString,
        bool useDefaultRetryOptions)
    {{
        _connectionString = connectionString;
        _useDefaultRetryOptions = useDefaultRetryOptions;
    }}

    public async Task<List<{(hasResult is null ? "object" : outputDtoName)}>> ExecuteAsync(
        {inputDtoName} input,
        DbConnection? existingConnection = null,
        CancellationToken ct = default)
    {{
        DbConnection? connection = existingConnection;
        if (connection == null)
        {{
            connection = new SqlConnection(_connectionString);
        }}
        using var cmd = connection.CreateCommand();
        cmd.CommandText = ""{p.FullName}"";
        cmd.CommandType = CommandType.StoredProcedure;

{addParams}

        OnBeforeExecute?.Invoke(cmd);

        if (connection.State != ConnectionState.Open)
            await connection.OpenAsync(ct).ConfigureAwait(false);

{readBlock}
    }}

    public Action<DbCommand>? OnBeforeExecute {{ get; set; }}

    private static void AddParam(DbCommand cmd, string name, System.Data.SqlDbType sqlDbType, object? value, bool isOutput)
    {{
        var p = new SqlParameter(name, sqlDbType)
        {{
            Direction = isOutput ? ParameterDirection.InputOutput : ParameterDirection.Input,
            Value = value ?? DBNull.Value
        }};
        cmd.Parameters.Add(p);
    }}

    {string.Join("\n", tvpMethods)}
}}";
        }

        private static string MapResultColumn(ResultColumnModel c, int i)
        {
            var isValueType = SqlModelTextMapper.IsValueType(c.SqlType);
            return (c.IsNullable, isValueType) switch
            {
                (true, true) => MapReaderGetterNullableValueType(c, i),
                (true, false) => MapReaderGetterNullableReferenceType(c, i),
                _ => MapReaderGetterValueType(c, i)
            };
        }

        private static string MapReaderGetterValueType(ResultColumnModel c, int i)
        {
            return $"                {SqlModelTextMapper.ToPascal(c.Name)} = reader.{SqlModelTextMapper.GetReaderMethod(c.SqlType)}({i}),";
        }

        private static string MapReaderGetterNullableReferenceType(ResultColumnModel c, int i)
        {
            return $"                {SqlModelTextMapper.ToPascal(c.Name)} = reader.IsDBNull({i}) ? null : reader.{SqlModelTextMapper.GetReaderMethod(c.SqlType)}({i}),";
        }

        private static string MapReaderGetterNullableValueType(ResultColumnModel c, int i)
        {
            return $"                {SqlModelTextMapper.ToPascal(c.Name)} = reader.IsDBNull({i}) ? default({ClrTypeMapper.ToClrType(c.SqlType, true)}) : reader.{SqlModelTextMapper.GetReaderMethod(c.SqlType)}({i}),";
        }

        private static string BuildParamAddition(ParameterModel par)
        {
            return IsTableValueParam(par)
                ? BuildParamAdditionForTableValueType(par)
                : BuildParamAdditionForValueType(par);
        }

        private static bool IsTableValueParam(ParameterModel par)
        {
            return par is { IsTableValued: true, TableTypeFullName: not null };
        }

        private static string BuildParamAdditionForValueType(ParameterModel par)
        {
            return $"        AddParam(cmd, \"{par.Name}\", System.Data.SqlDbType.{SqlModelTextMapper.ToSqlDbType(par.SqlType)}, input.{SqlModelTextMapper.ToPascal(SqlModelTextMapper.TrimAt(par.Name))}, {par.IsOutput.ToString().ToLowerInvariant()});";
        }

        private static string BuildParamAdditionForTableValueType(ParameterModel par)
        {
            return $"        cmd.Parameters.Add(ToTvp{SqlModelTextMapper.ToPascal(par.Name)}(\"{par.Name}\", \"{par.TableTypeFullName}\", input.{SqlModelTextMapper.ToPascal(SqlModelTextMapper.TrimAt(par.Name))}));";
        }

        private static string GenerateTableValueParamMapMethod(string paramName, string clrType)
        {
            var columns = clrType.Trim().Trim(']').Trim('[').Trim('(', ')').Split(',')
                .Select(tupleTypePart => tupleTypePart.Trim().Split(' '))
                .Select(c => (ClrColType: c[0].Trim().Trim('(',')'),ColName: c[1].Trim()))
                .ToArray();
            var columnsToAdd = columns
                .Select((col) => $"            table.Columns.Add(\"{col.ColName}\", typeof({col.ClrColType}));")
                .ToArray();
            var valuesToAdd = columns
                .Select((col) => $"r.{col.ColName}")
                .ToArray();
            return
$@"
        private static SqlParameter ToTvp{SqlModelTextMapper.ToPascal(paramName)}(string name,
            string typeName,
            {clrType} rows)
        {{
            var table = new System.Data.DataTable();
{string.Join("\n", columnsToAdd)}
            foreach (var r in rows) 
            {{
                table.Rows.Add({string.Join(", ", valuesToAdd)}); 
            }}
            return new SqlParameter(name, SqlDbType.Structured) {{ TypeName = typeName, Value = table }};
        }}        
";
        }
    }
}